apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: bird-api-hpa
  namespace: bird-api
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: bird-api
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 70
